#!/bin/bash

set -e
set -o pipefail

echo "Testing: $1"
gcc -std=c11 -Wall -Werror -Wno-unused -g -I.. "$1" -o $(basename "$1" .c)
./$(basename "$1" .c)
# If any of the above exits non-zero, we crash before here.
echo "Pass: $1"
rm $(basename "$1" .c)
