#!/bin/bash

set -e
set -o pipefail
set -x

echo "Testing: $1"
"$CC" -std=c11 -Wall -Wpedantic -Werror -Wno-unused -g -I.. "$1" -o $(basename "$1" .c)
./$(basename "$1" .c)
# If any of the above exits non-zero, we crash before here.
echo "Pass: $1"
rm $(basename "$1" .c)
