language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
compiler:
  - gcc
  - clang
before_install:
  - eval "${MATRIX_EVAL}"
script: cd test && ./test
